version: "3.8"

services:
  document-extractor:
    image: document-extractor:latest
    container_name: document-extractor
    user: "99:100"
    restart: unless-stopped

    # Single /data mount with subfolders
    volumes:
      - /mnt/user/appdata/document-extractor/data:/data

    environment:
      - PUID=99
      - PGID=100
      - TZ=America/New_York

    healthcheck:
      test: ["CMD-SHELL", "/app/scripts/healthcheck.sh"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
